/**
 * Reco Servicios — Jobs & Service Registry
 * Maps user needs ("Jobs to be done") to services.
 * A service can appear in multiple Jobs without duplication.
 */

const JOBS = Object.freeze({
  VALORAR: 'valorar',
  REVISAR_OPERACION: 'revisar-operacion',
  VERIFICAR: 'verificar',
  PAGAR_FINANCIAR: 'pagar-financiar',
  MEJORAR: 'mejorar',
  MANTENER: 'mantener',
  ADMINISTRAR: 'administrar',
});

const JOB_DEFINITIONS = [
  {
    id: JOBS.VALORAR,
    title: 'Valorar mi propiedad',
    icon: '📊',
    description: 'Quiero saber cuánto vale mi propiedad.',
    ctaPrimary: { label: 'Calcular valor', action: 'job_valorar_primary' },
    ctaSecondary: { label: 'Solicitar una tasación', action: 'job_valorar_secondary' },
    priority: 1,
    gradient: 'linear-gradient(135deg,#1A4FBF 0%,#0E2A5C 100%)',
    services: ['reco-estimate', 'tasacion-express', 'tasacion-virtual', 'tasacion-presencial'],
    relatedServices: [
      { id: 'foto-premium', hook: '¿Quieres venderla?' },
      { id: 'reco-agent', hook: '¿Buscas un agente?' },
      { id: 'credito-hipotecario', hook: '¿Necesitas financiar?' },
    ],
  },
  {
    id: JOBS.REVISAR_OPERACION,
    title: 'Revisar una compra o venta',
    icon: '🔎',
    description: 'Estoy por hacer una operación inmobiliaria y quiero tomar una mejor decisión.',
    ctaPrimary: { label: 'Revisar mi operación', action: 'job_revisar_primary' },
    ctaSecondary: null,
    priority: 2,
    gradient: 'linear-gradient(135deg,#0E4A3A 0%,#1A6B4A 100%)',
    services: ['reco-agent', 'tasacion-presencial', 'property-check', 'estudio-titulos', 'due-diligence', 'asesoria-legal', 'minuta'],
    relatedServices: [
      { id: 'credito-hipotecario', hook: '¿Necesitas financiar?' },
      { id: 'foto-premium', hook: 'Mejora cómo se ve' },
      { id: 'seguro-hogar', hook: 'Protege tu inversión' },
    ],
  },
  {
    id: JOBS.VERIFICAR,
    title: 'Verificar una propiedad',
    icon: '🛡️',
    description: 'Quiero saber si una propiedad es segura para comprar.',
    ctaPrimary: { label: 'Verificar propiedad', action: 'job_verificar_primary' },
    ctaSecondary: null,
    priority: 3,
    gradient: 'linear-gradient(135deg,#7C3AED 0%,#4C1D95 100%)',
    services: ['property-check', 'revision-registral', 'estudio-titulos', 'due-diligence', 'asesoria-legal'],
    relatedServices: [
      { id: 'tasacion-presencial', hook: 'Conoce su valor real' },
      { id: 'credito-hipotecario', hook: '¿Necesitas financiar?' },
      { id: 'reco-agent', hook: 'Encuentra un agente' },
    ],
  },
  {
    id: JOBS.PAGAR_FINANCIAR,
    title: 'Pagar o financiar',
    icon: '💳',
    description: 'Necesito pagar, financiar o proteger una operación inmobiliaria.',
    ctaPrimary: { label: 'Pagar alquiler', action: 'job_pagar_primary' },
    ctaSecondary: { label: 'Simular crédito', action: 'job_pagar_secondary' },
    priority: 4,
    gradient: 'linear-gradient(135deg,#0369A1 0%,#0C4A6E 100%)',
    services: ['pago-alquiler', 'credito-hipotecario', 'seguro-hogar', 'seguro-alquiler'],
    relatedServices: [
      { id: 'property-management', hook: 'Administra tus propiedades' },
      { id: 'property-check', hook: 'Verifica antes de comprar' },
    ],
  },
  {
    id: JOBS.MEJORAR,
    title: 'Mejorar mi publicación',
    icon: '📸',
    description: 'Quiero que mi propiedad se vea mejor para venderla o alquilarla.',
    ctaPrimary: { label: 'Mejorar mi publicación', action: 'job_mejorar_primary' },
    ctaSecondary: null,
    priority: 5,
    gradient: 'linear-gradient(135deg,#B45309 0%,#78350F 100%)',
    services: ['foto-basica', 'foto-premium', 'video-recorrido', 'tour-virtual-ia', 'home-staging-ia', 'pack-reco-visual', 'remodelacion'],
    relatedServices: [
      { id: 'reco-estimate', hook: '¿Cuánto vale ahora?' },
      { id: 'reco-agent', hook: 'Encuentra un agente' },
    ],
  },
  {
    id: JOBS.MANTENER,
    title: 'Mantener mi propiedad',
    icon: '🔧',
    description: 'Necesito reparar, limpiar, mejorar o mantener mi propiedad.',
    ctaPrimary: { label: 'Encontrar un servicio', action: 'job_mantener_primary' },
    ctaSecondary: null,
    priority: 6,
    gradient: 'linear-gradient(135deg,#DC2626 0%,#991B1B 100%)',
    services: ['limpieza', 'gasfiteria', 'electricista', 'pintura', 'mudanza', 'remodelacion', 'aire-acondicionado', 'carpinteria', 'camaras', 'jardineria', 'impermeabilizacion'],
    relatedServices: [
      { id: 'property-management', hook: 'Administra tus propiedades' },
      { id: 'seguro-hogar', hook: 'Protege tu inversión' },
    ],
  },
  {
    id: JOBS.ADMINISTRAR,
    title: 'Administrar mi propiedad',
    icon: '🏢',
    description: 'Quiero administrar mejor mis propiedades.',
    ctaPrimary: { label: 'Administrar mi propiedad', action: 'job_administrar_primary' },
    ctaSecondary: null,
    priority: 7,
    gradient: 'linear-gradient(135deg,#475569 0%,#1E293B 100%)',
    services: ['property-management', 'pago-alquiler', 'mantenimiento-marketplace', 'seguro-hogar'],
    relatedServices: [
      { id: 'reco-estimate', hook: '¿Cuánto valen tus propiedades?' },
      { id: 'seguro-hogar', hook: 'Protege tu inversión' },
      { id: 'reco-agent', hook: 'Encuentra un agente' },
    ],
  },
];

const SERVICE_REGISTRY = [
  // --- Valoración ---
  {
    id: 'reco-estimate',
    name: 'Reco Estimate',
    description: 'Estimación de valor basada en +40K tasaciones Vanet. Instantánea y gratuita.',
    icon: '📊',
    jobs: [JOBS.VALORAR],
    category: 'tasaciones',
    price: 'Gratis',
    priceType: 'free',
    monetizationModel: 'free',
    status: 'available',
    featured: true,
    tags: ['Gratis', 'Instantáneo'],
    cta: { label: 'Probar gratis', action: 'navigate_tasaciones' },
    navigateTo: CATEGORIES.TASACIONES,
  },
  {
    id: 'tasacion-express',
    name: 'Tasación Express',
    description: 'Informe con IA + revisión humana en 24h. Ideal para pre-compra y negociación.',
    icon: '⚡',
    jobs: [JOBS.VALORAR, JOBS.REVISAR_OPERACION],
    category: 'tasaciones',
    price: 'S/ 149',
    priceType: 'fixed',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: ['24h'],
    cta: { label: 'Solicitar', action: 'navigate_tasaciones' },
    navigateTo: CATEGORIES.TASACIONES,
  },
  {
    id: 'tasacion-virtual',
    name: 'Tasación Virtual',
    description: 'Videollamada con tasador REPEV. Informe firmado válido para créditos.',
    icon: '📹',
    jobs: [JOBS.VALORAR, JOBS.REVISAR_OPERACION, JOBS.VERIFICAR],
    category: 'tasaciones',
    price: 'S/ 349',
    priceType: 'fixed',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: ['Recomendado'],
    cta: { label: 'Agendar', action: 'navigate_tasaciones' },
    navigateTo: CATEGORIES.TASACIONES,
  },
  {
    id: 'tasacion-presencial',
    name: 'Tasación Presencial',
    description: 'Visita técnica al inmueble. Aceptada por BCP, BBVA, Interbank, Scotiabank.',
    icon: '🏠',
    jobs: [JOBS.VALORAR, JOBS.REVISAR_OPERACION, JOBS.VERIFICAR],
    category: 'tasaciones',
    price: 'S/ 590',
    priceType: 'fixed',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: ['Bancaria'],
    cta: { label: 'Reservar visita', action: 'navigate_tasaciones' },
    navigateTo: CATEGORIES.TASACIONES,
  },

  // --- Legal / Verificación ---
  {
    id: 'property-check',
    name: 'Reco Property Check',
    description: 'Verificación integral de una propiedad antes de comprar. Registral, municipal y legal.',
    icon: '🛡️',
    jobs: [JOBS.VERIFICAR, JOBS.REVISAR_OPERACION],
    category: 'legal',
    price: 'Desde S/ 200',
    priceType: 'starting_at',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: true,
    tags: ['Recomendado'],
    cta: { label: 'Verificar', action: 'navigate_legal' },
    navigateTo: CATEGORIES.LEGAL,
  },
  {
    id: 'revision-registral',
    name: 'Revisión registral',
    description: 'Búsqueda en SUNARP de la partida registral del inmueble.',
    icon: '🏛️',
    jobs: [JOBS.VERIFICAR],
    category: 'legal',
    price: 'S/ 80',
    priceType: 'fixed',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Solicitar', action: 'navigate_legal' },
    navigateTo: CATEGORIES.LEGAL,
  },
  {
    id: 'estudio-titulos',
    name: 'Estudio de títulos',
    description: 'Verificación de cadena de titularidad en SUNARP. Identifica cargas, gravámenes e hipotecas.',
    icon: '🏛️',
    jobs: [JOBS.VERIFICAR, JOBS.REVISAR_OPERACION],
    category: 'legal',
    price: 'S/ 200 – 400',
    priceType: 'range',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Solicitar', action: 'navigate_legal' },
    navigateTo: CATEGORIES.LEGAL,
  },
  {
    id: 'due-diligence',
    name: 'Due diligence documental',
    description: 'Auditoría completa: títulos, municipalidad, SUNARP, deudas tributarias.',
    icon: '📑',
    jobs: [JOBS.VERIFICAR, JOBS.REVISAR_OPERACION],
    category: 'legal',
    price: 'S/ 350 – 800',
    priceType: 'range',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Solicitar', action: 'navigate_legal' },
    navigateTo: CATEGORIES.LEGAL,
  },
  {
    id: 'asesoria-legal',
    name: 'Asesoría legal inmobiliaria',
    description: 'Consulta con abogado especializado en derecho inmobiliario. Sesión de 45 min.',
    icon: '⚖️',
    jobs: [JOBS.VERIFICAR, JOBS.REVISAR_OPERACION],
    category: 'legal',
    price: 'S/ 150',
    priceType: 'fixed',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Agendar', action: 'navigate_legal' },
    navigateTo: CATEGORIES.LEGAL,
  },
  {
    id: 'minuta',
    name: 'Minuta de compraventa',
    description: 'Elaboración de minuta para inscripción en Registros Públicos.',
    icon: '📄',
    jobs: [JOBS.REVISAR_OPERACION],
    category: 'legal',
    price: 'S/ 300 – 500',
    priceType: 'range',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Ver detalles', action: 'navigate_legal' },
    navigateTo: CATEGORIES.LEGAL,
  },

  // --- Pagos y Finanzas ---
  {
    id: 'pago-alquiler',
    name: 'Pago de alquiler',
    description: 'Paga tu alquiler con tarjeta de crédito. Acumula millas y difiere en cuotas.',
    icon: '💳',
    jobs: [JOBS.PAGAR_FINANCIAR, JOBS.ADMINISTRAR],
    category: 'pagos',
    price: '2.9% comisión',
    priceType: 'commission',
    monetizationModel: 'commission',
    status: 'available',
    featured: true,
    tags: ['Core'],
    cta: { label: 'Pagar alquiler', action: 'navigate_pagos' },
    navigateTo: CATEGORIES.PAGOS,
  },
  {
    id: 'credito-hipotecario',
    name: 'Crédito hipotecario',
    description: 'Comparador de TCEA en tiempo real. Convenios con BCP, BBVA, Interbank, Scotiabank.',
    icon: '🏦',
    jobs: [JOBS.PAGAR_FINANCIAR, JOBS.REVISAR_OPERACION, JOBS.VERIFICAR],
    category: 'finanzas',
    price: 'Sin costo',
    priceType: 'free',
    monetizationModel: 'referral',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Simular crédito', action: 'navigate_finanzas' },
    navigateTo: CATEGORIES.FINANZAS,
  },
  {
    id: 'seguro-hogar',
    name: 'Seguro de hogar',
    description: 'Contra incendios, sismos y robo. Alianza con Rímac, Pacífico y La Positiva.',
    icon: '🛡️',
    jobs: [JOBS.PAGAR_FINANCIAR, JOBS.ADMINISTRAR],
    category: 'finanzas',
    price: 'Desde S/ 25/mes',
    priceType: 'starting_at',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Cotizar', action: 'navigate_finanzas' },
    navigateTo: CATEGORIES.FINANZAS,
  },
  {
    id: 'seguro-alquiler',
    name: 'Seguro de alquiler',
    description: 'Protección ante impago de renta. Cobertura de hasta 12 meses.',
    icon: '🔐',
    jobs: [JOBS.PAGAR_FINANCIAR],
    category: 'finanzas',
    price: 'Desde S/ 35/mes',
    priceType: 'starting_at',
    monetizationModel: 'commission',
    status: 'coming_soon',
    featured: false,
    tags: ['Próximamente'],
    cta: { label: 'Próximamente', action: 'coming_soon' },
    navigateTo: null,
  },

  // --- Fotografía / Visual ---
  {
    id: 'foto-basica',
    name: 'Fotografía básica',
    description: '15 fotos HDR editadas. Entrega en 24h. Ideal para alquiler o venta rápida.',
    icon: '📷',
    jobs: [JOBS.MEJORAR],
    category: 'fotografia',
    price: 'S/ 199',
    priceType: 'fixed',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Agendar', action: 'navigate_fotografia' },
    navigateTo: CATEGORIES.FOTOGRAFIA,
  },
  {
    id: 'foto-premium',
    name: 'Fotografía premium',
    description: '30 fotos HDR + retoque profesional + plano de distribución. Entrega en 48h.',
    icon: '📸',
    jobs: [JOBS.MEJORAR, JOBS.REVISAR_OPERACION],
    category: 'fotografia',
    price: 'S/ 399',
    priceType: 'fixed',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: true,
    tags: ['Recomendado'],
    cta: { label: 'Agendar', action: 'navigate_fotografia' },
    navigateTo: CATEGORIES.FOTOGRAFIA,
  },
  {
    id: 'video-recorrido',
    name: 'Video recorrido',
    description: 'Video profesional de 60-90s. Música con licencia, color grading cinematográfico.',
    icon: '🎥',
    jobs: [JOBS.MEJORAR],
    category: 'fotografia',
    price: 'S/ 349',
    priceType: 'fixed',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Agendar', action: 'navigate_fotografia' },
    navigateTo: CATEGORIES.FOTOGRAFIA,
  },
  {
    id: 'tour-virtual-ia',
    name: 'Tour virtual IA',
    description: 'Tour inmersivo generado con IA a partir de fotos existentes, sin visita presencial.',
    icon: '🌐',
    jobs: [JOBS.MEJORAR],
    category: 'fotografia',
    price: 'S/ 149',
    priceType: 'fixed',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: ['IA'],
    cta: { label: 'Solicitar', action: 'navigate_fotografia' },
    navigateTo: CATEGORIES.FOTOGRAFIA,
  },
  {
    id: 'home-staging-ia',
    name: 'Home staging virtual',
    description: 'Amobla virtualmente cualquier ambiente con IA. Toggle amoblado/real en la ficha.',
    icon: '🛋️',
    jobs: [JOBS.MEJORAR],
    category: 'fotografia',
    price: 'S/ 199',
    priceType: 'fixed',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: ['IA'],
    cta: { label: 'Solicitar', action: 'navigate_fotografia' },
    navigateTo: CATEGORIES.FOTOGRAFIA,
  },
  {
    id: 'pack-reco-visual',
    name: 'Pack Reco Visual',
    description: 'Foto premium + video + tour IA + staging virtual. 25% de descuento.',
    icon: '🎯',
    jobs: [JOBS.MEJORAR],
    category: 'fotografia',
    price: 'S/ 899',
    priceType: 'fixed',
    monetizationModel: 'fixed_price',
    status: 'available',
    featured: false,
    tags: ['Pack'],
    cta: { label: 'Ver pack', action: 'navigate_fotografia' },
    navigateTo: CATEGORIES.FOTOGRAFIA,
  },

  // --- Agente ---
  {
    id: 'reco-agent',
    name: 'Reco Agent',
    description: 'Encuentra un agente inmobiliario verificado para tu operación.',
    icon: '🏠',
    jobs: [JOBS.REVISAR_OPERACION, JOBS.VALORAR, JOBS.MEJORAR],
    category: 'reco_agent',
    price: 'Sin costo',
    priceType: 'free',
    monetizationModel: 'success_fee',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Buscar agente', action: 'navigate_agentes' },
    navigateTo: CATEGORIES.RECO_AGENT,
  },

  // --- Mantenimiento ---
  {
    id: 'limpieza',
    name: 'Limpieza profunda',
    description: 'Limpieza integral de departamentos y casas.',
    icon: '🧹',
    jobs: [JOBS.MANTENER],
    category: 'mantenimiento',
    price: 'Desde S/ 99',
    priceType: 'starting_at',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Solicitar', action: 'navigate_mantenimiento' },
    navigateTo: CATEGORIES.MANTENIMIENTO,
  },
  {
    id: 'gasfiteria',
    name: 'Gasfitería',
    description: 'Reparación de tuberías, desatoros, instalación de sanitarios y grifería.',
    icon: '🔧',
    jobs: [JOBS.MANTENER],
    category: 'mantenimiento',
    price: 'Desde S/ 70',
    priceType: 'starting_at',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: ['24/7'],
    cta: { label: 'Solicitar', action: 'navigate_mantenimiento' },
    navigateTo: CATEGORIES.MANTENIMIENTO,
  },
  {
    id: 'electricista',
    name: 'Electricista certificado',
    description: 'Instalaciones eléctricas, reparaciones, tableros y cableado.',
    icon: '⚡',
    jobs: [JOBS.MANTENER],
    category: 'mantenimiento',
    price: 'Desde S/ 60',
    priceType: 'starting_at',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: ['24/7'],
    cta: { label: 'Solicitar', action: 'navigate_mantenimiento' },
    navigateTo: CATEGORIES.MANTENIMIENTO,
  },
  {
    id: 'pintura',
    name: 'Pintura interior',
    description: 'Pintura de interiores, empaste, acabados.',
    icon: '🎨',
    jobs: [JOBS.MANTENER],
    category: 'mantenimiento',
    price: 'Desde S/ 12/m²',
    priceType: 'per_unit',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Cotizar', action: 'navigate_mantenimiento' },
    navigateTo: CATEGORIES.MANTENIMIENTO,
  },
  {
    id: 'mudanza',
    name: 'Mudanzas y embalaje',
    description: 'Servicio integral de mudanza con embalaje profesional.',
    icon: '📦',
    jobs: [JOBS.MANTENER],
    category: 'mantenimiento',
    price: 'Cotización',
    priceType: 'quote',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Cotizar', action: 'navigate_mantenimiento' },
    navigateTo: CATEGORIES.MANTENIMIENTO,
  },
  {
    id: 'remodelacion',
    name: 'Remodelación integral',
    description: 'Remodelación completa con diseño, materiales y mano de obra.',
    icon: '🏗️',
    jobs: [JOBS.MANTENER, JOBS.MEJORAR],
    category: 'mantenimiento',
    price: 'Cotización',
    priceType: 'quote',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: ['Premium'],
    cta: { label: 'Cotizar', action: 'navigate_mantenimiento' },
    navigateTo: CATEGORIES.MANTENIMIENTO,
  },
  {
    id: 'aire-acondicionado',
    name: 'Aire acondicionado',
    description: 'Instalación, mantenimiento y reparación de aire acondicionado.',
    icon: '❄️',
    jobs: [JOBS.MANTENER],
    category: 'mantenimiento',
    price: 'Desde S/ 89',
    priceType: 'starting_at',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Solicitar', action: 'navigate_mantenimiento' },
    navigateTo: CATEGORIES.MANTENIMIENTO,
  },
  {
    id: 'carpinteria',
    name: 'Carpintería y melamine',
    description: 'Muebles a medida, closets, cocinas y reparaciones.',
    icon: '🪜',
    jobs: [JOBS.MANTENER],
    category: 'mantenimiento',
    price: 'Desde S/ 80',
    priceType: 'starting_at',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Solicitar', action: 'navigate_mantenimiento' },
    navigateTo: CATEGORIES.MANTENIMIENTO,
  },
  {
    id: 'camaras',
    name: 'Instalación de cámaras',
    description: 'Sistemas de videovigilancia y CCTV.',
    icon: '📹',
    jobs: [JOBS.MANTENER],
    category: 'mantenimiento',
    price: 'Desde S/ 250',
    priceType: 'starting_at',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Solicitar', action: 'navigate_mantenimiento' },
    navigateTo: CATEGORIES.MANTENIMIENTO,
  },
  {
    id: 'jardineria',
    name: 'Jardinería y paisajismo',
    description: 'Diseño, mantenimiento y cuidado de jardines.',
    icon: '🌿',
    jobs: [JOBS.MANTENER],
    category: 'mantenimiento',
    price: 'Desde S/ 100',
    priceType: 'starting_at',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Solicitar', action: 'navigate_mantenimiento' },
    navigateTo: CATEGORIES.MANTENIMIENTO,
  },
  {
    id: 'impermeabilizacion',
    name: 'Impermeabilización',
    description: 'Protección contra filtraciones y reparación de techos.',
    icon: '💧',
    jobs: [JOBS.MANTENER],
    category: 'mantenimiento',
    price: 'Desde S/ 18/m²',
    priceType: 'per_unit',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Cotizar', action: 'navigate_mantenimiento' },
    navigateTo: CATEGORIES.MANTENIMIENTO,
  },

  // --- Property Management ---
  {
    id: 'property-management',
    name: 'Property Management',
    description: 'Gestiona tus propiedades, alquileres, documentos y mantenimiento.',
    icon: '🏢',
    jobs: [JOBS.ADMINISTRAR],
    category: 'property_management',
    price: 'Gratis',
    priceType: 'free',
    monetizationModel: 'free',
    status: 'available',
    featured: true,
    tags: [],
    cta: { label: 'Administrar', action: 'navigate_propiedades' },
    navigateTo: CATEGORIES.PROPERTY_MANAGEMENT,
  },

  // --- Maintenance Marketplace (aggregate) ---
  {
    id: 'mantenimiento-marketplace',
    name: 'Marketplace de mantenimiento',
    description: 'Cotiza, agenda y califica proveedores de mantenimiento verificados.',
    icon: '🔧',
    jobs: [JOBS.ADMINISTRAR],
    category: 'mantenimiento',
    price: 'Desde S/ 60',
    priceType: 'starting_at',
    monetizationModel: 'commission',
    status: 'available',
    featured: false,
    tags: [],
    cta: { label: 'Ver servicios', action: 'navigate_mantenimiento' },
    navigateTo: CATEGORIES.MANTENIMIENTO,
  },
];

// --- Query helpers ---

function getJobDefinitions() {
  return JOB_DEFINITIONS.slice().sort((a, b) => a.priority - b.priority);
}

function getJobById(jobId) {
  return JOB_DEFINITIONS.find(j => j.id === jobId) || null;
}

function getServicesByJob(jobId) {
  const job = getJobById(jobId);
  if (!job) return [];
  return job.services
    .map(svcId => SERVICE_REGISTRY.find(s => s.id === svcId))
    .filter(Boolean);
}

function getRelatedServicesForJob(jobId) {
  const job = getJobById(jobId);
  if (!job) return [];
  return job.relatedServices
    .map(rel => {
      const svc = SERVICE_REGISTRY.find(s => s.id === rel.id);
      return svc ? { ...svc, hook: rel.hook } : null;
    })
    .filter(Boolean);
}

function getRegistryServiceById(svcId) {
  return SERVICE_REGISTRY.find(s => s.id === svcId) || null;
}

function getJobsForService(svcId) {
  return JOB_DEFINITIONS.filter(j => j.services.includes(svcId));
}

function getJobsForProperty() {
  return [JOBS.VALORAR, JOBS.VERIFICAR, JOBS.PAGAR_FINANCIAR, JOBS.MEJORAR, JOBS.MANTENER, JOBS.ADMINISTRAR]
    .map(getJobById)
    .filter(Boolean);
}
